# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20170724_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DegreePrograms',
            new_name='DegreeProgram',
        ),
        migrations.RenameModel(
            old_name='Offices',
            new_name='Office',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
